// @ts-check
// `@type` JSDoc annotations allow editor autocompletion and type checking
// (when paired with `@ts-check`).
// There are various equivalent ways to declare your Docusaurus config.
// See: https://docusaurus.io/docs/api/docusaurus-config

import { themes as prismThemes } from "prism-react-renderer";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Official Phoenix Wiki",
  tagline: "Dinosaurs are cool",
  favicon: "img/favicon.ico",

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // Set the production url of your site here
  url: "https://docs.phoenixdevt.fr",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "facebook", // Usually your GitHub org/user name.
  projectName: "docusaurus", // Usually your repo name.

  onBrokenLinks: "throw",

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        // Note: additional docs instances must be added via `plugins` (not inside the preset options).

        theme: {
          customCss: "./src/css/custom.css",
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Replace with your project's social card
      image: "img/docusaurus-social-card.jpg",
      colorMode: {
        respectPrefersColorScheme: true,
      },
      navbar: {
        title: "Phoenix Wiki",
        logo: {
          alt: "My Site Logo",
          src: "img/phoenix_def.png",
        },
        items: [
          {
            type: "docSidebar",
            sidebarId: "autogeneratedSidebar",
            docsPluginId: "mmoitems",
            position: "left",
            label: "MMOItems",
          },
          {
            type: "docSidebar",
            sidebarId: "autogeneratedSidebar",
            docsPluginId: "mmocore",
            position: "left",
            label: "MMOCore",
          },
          {
            type: "docSidebar",
            sidebarId: "autogeneratedSidebar",
            docsPluginId: "mmoinventory",
            position: "left",
            label: "MMOInventory",
          },
          {
            type: "docSidebar",
            sidebarId: "autogeneratedSidebar",
            docsPluginId: "mmoprofiles",
            position: "left",
            label: "MMOProfiles",
          },
          {
            type: "docSidebar",
            sidebarId: "autogeneratedSidebar",
            docsPluginId: "mmolib",
            position: "left",
            label: "MythicLib",
          },

          {
            href: "https://github.com/facebook/docusaurus",
            label: "GitHub",
            position: "right",
          },
        ],
      },
      footer: {
        style: "dark",
        links: [
          {
            title: "Docs",
            items: [
              {
                label: "Tutorial",
                to: "/docs/intro",
              },
            ],
          },
          {
            title: "Community",
            items: [
              {
                label: "Stack Overflow",
                href: "https://stackoverflow.com/questions/tagged/docusaurus",
              },
              {
                label: "Discord",
                href: "https://discordapp.com/invite/docusaurus",
              },
              {
                label: "X",
                href: "https://x.com/docusaurus",
              },
            ],
          },
          {
            title: "More",
            items: [
              {
                label: "Blog",
                to: "/blog",
              },
              {
                label: "GitHub",
                href: "https://github.com/facebook/docusaurus",
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Phoenix Development. Built with <a href="https://docusaurus.io" target="_blank" rel="noopener">Docusaurus</a>`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
      },
    }),
};

// Additional plugins (outside preset options)
config.plugins = [
  [
    "@docusaurus/plugin-content-docs",
    {
      id: "mmoitems",
      path: "docs_mmoitems",
      routeBasePath: "mmoitems",
      sidebarPath: require.resolve("./sidebars.js"),
      editUrl: "https://github.com/facebook/.......",
    },
  ],
  [
    "@docusaurus/plugin-content-docs",
    {
      id: "mmocore",
      path: "docs_mmocore",
      routeBasePath: "mmocore",
      sidebarPath: require.resolve("./sidebars.js"),
      editUrl: "https://github.com/facebook/.......",
    },
  ],
  [
    "@docusaurus/plugin-content-docs",
    {
      id: "mmoinventory",
      path: "docs_mmoinventory",
      routeBasePath: "mmoinventory",
      sidebarPath: require.resolve("./sidebars.js"),
      editUrl: "https://github.com/facebook/.......",
    },
  ],
  [
    "@docusaurus/plugin-content-docs",
    {
      id: "mmoprofiles",
      path: "docs_mmoprofiles",
      routeBasePath: "mmoprofiles",
      sidebarPath: require.resolve("./sidebars.js"),
      editUrl: "https://github.com/facebook/.......",
    },
  ],
  [
    "@docusaurus/plugin-content-docs",
    {
      id: "mmolib",
      path: "docs_mmolib",
      routeBasePath: "mmolib",
      sidebarPath: require.resolve("./sidebars.js"),
      editUrl: "https://github.com/facebook/.......",
    },
  ],
];

export default config;
